### ISSUE TITLE
Installer - User credentials default to demo

### ISSUE THREAD

**Issue by andrewcouling** [timschofield/webERP#307]
I have just completed an installation of latest code fetched from master branch, but have ran into an issue.

It was a fresh installation, into an empty database.
I did not install the demo data.
Although I entered my preferred user ID, email address, and password in the installation process, once the installer had completed, these credentials were not accepted at the login page.
Within the login page, I noticed the demo credentials prompt e.g. admin/weberp, so tried to gain access using these, and was able to log in.
By checking in phpMyAdmin I have verified that the demo data was not installed into the database (no items, customers, or suppliers), and 'admin' is the only user account.

In the resultant config.php file:
`$AllowDemoMode = True;` **- I didn't select to install the demo data**
`$SysAdminEmail = the email i entered in the installer` **- OK**
`$AllowCompanySelectionBox = 'ShowSelectionBox';` **- Imho, this is required only if there are multiple companies installed**
`$DefaultTheme = 'xenos';` **- Although this was present in config.php, when i logged in for the first time, the theme named 'Default' was selected. Is this redundant, as default theme is defined in SystemParameters.php ?**
`$DefaultClock = 12;` **- Like default theme, shouldn't this be defined in SystemParameters.php ? If not, should we offer a choice between 12/24 hour clock during the installation process?**

`//Installed companies`
`$CompanyList[0] = array('database'=>'weberpdemo' ,'company'=>'WebERP Demo Company' );` **- Displays here even though i did not want the demo to be installed**
`$CompanyList[1] = array('database'=>'your_db' ,'company'=>'Your Company inc' );`  **- Does not seem to have been affected by my database name/user or company name input**

Additional things I spotted:
1. As I declined to install the demo data, I was surprised to see 'webERPDemo Company Ltd' available as an option in the 'Company' dropdown box on the login page, in addition to my chosen company name.
2. On page 5 of the installer, the Company Name field appears to inherit its value from either 'database name' or 'database user' from the previous page (sorry I cant determine which, as these inputs are identical for my set-up), and I don't understand why. I would expect that most users would want to input a real company name here, instead of a database name/username.
3. Current version shown in footer is 4.15.1+10
4. A new directory has been created in companies, and my custom logo has been uploaded successfully (I have verified by downloading the logo image), but it doesn't display correctly in the top left corner of the page header. Changing between themes doesn't impact this: 
![image](https://github.com/user-attachments/assets/4b643841-9b3f-45aa-8959-5fc6f4444c44)

5. Without any post-install configuration, on Stocks.php, I unexpectedly see fields for french language input, even though I selected english language during the installation process:
![image](https://github.com/user-attachments/assets/487f890a-662f-4515-9e3e-16afaf9988e0)

6.  After creating a stock category, I try to create a new stock item on Stocks.php. The following page doesn't render correctly (only a page heading displays), and the new item is not created. The following web server error is generated. I gather this is because a Tax Category is not defined yet, but I feel there should be a message box prompting me to create one.

`erp-repo.handloomholdings.com [Fri Dec 13 01:03:19 2024] [error] [client 212.56.99.66:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`weberp-repo-353037355684`.`stockmaster`, CONSTRAINT `stockmaster_ibfk_2` FOREIGN KEY (`taxcatid`) REFERENCES `taxcategories` (`taxcatid`)) in /home/sites/3a/2/2b806fa8d9/public_html/erp-repo/includes/ConnectDB_mariadb.inc:58\nStack trace:\n#0 /home/sites/3a/2/2b806fa8d9/public_html/erp-repo/includes/ConnectDB_mariadb.inc(58): mysqli_query(Object(mysqli), 'INSERT INTO sto...')\n#1 /home/sites/3a/2/2b806fa8d9/public_html/erp-repo/Stocks.php(660): DB_query('INSERT INTO sto...', 'The item could ...', 'The SQL that wa...', '', true)\n#2 {main}\n  thrown in /home/sites/3a/2/2b806fa8d9/public_html/erp-repo/includes/ConnectDB_mariadb.inc on line 58'`

7.  On Stocks.php, after creating a Tax Category, I am able to create an item without selecting a Unit of Measure. Is it correct that this field is not mandatory? If it should be, can there be a warning message prompting me to define units of measure?
8. After I have created an item, an open search for any item (or specific to an item code) in SelectProduct.php returns zero items, although I can see in the database that an item has been created. I receive the message "No stock items were returned by this search please re-enter alternative criteria to try again".

**Comment by andrewcouling** [comment]
Please let me know if I should split this report into separate issues

**Comment by dalers** [comment]
> I unexpectedly see fields for french language input,

I have found the same behavior, I suspect this feature applies only to Canada where both English and French descriptions for an Item must be maintained, and presume everyone else simply ignores the "Français Description" and "Français Long Description" fields.

It may be the feature works generically as "any language and French" field, but then either a configuration variable exists to use the French descriptions in standard reports, or any reports that needed to use the French fields were essentially custom created and site-specific, and are not managed by the webERP project.

**Comment by andrewcouling** [comment]
> Without any post-install configuration, on Stocks.php, I unexpectedly see fields for french language input, even though I selected english language during the installation process:

Fixes in commit: https://github.com/timschofield/webERP/commit/715df566b24eb62c2f75595f7e978eb1c3929a7f

**Comment by andrewcouling** [comment]
> Current version shown in footer is 4.15.1+10

Fixed in commit: https://github.com/timschofield/webERP/commit/557a4165bcdc4e53f029b20fe4fa1da12fa2fc2c

Ref discussion #211

**Comment by timschofield** [comment]
Can this issue be closed?

**Comment by dalers** [comment]
It depends...  ;-)   the discussion has been related largely to running the installer to create a new system. Using the latest commit, I see my "old" database still shows text fields for "Français Description:" and "Français Long Description:", although they have never been entered for any item. What is created with a new db? Is there a new config value to select if these are shown, or the language for the "alternate" languate description and long description? Does there need to be a script to trim the fields from an old db?

Btw, when navigating between Items and viewing individual Item details, I seem to constantly be triggering zoom/unzoom of an images moving the mouse around. I expect I'll get used to it but it might be nice to have a config value to turn off "auto-zoom" and only zoom an image when clicked. Fwiw.....

**Comment by timschofield** [comment]
Hi @dalers 
I have removed the translated inventory items. They can of course be added back in SystemParameters

Tim

**Comment by dalers** [comment]
> I have removed the translated inventory items. They can of course be added back in SystemParameters

Thanks Tim. 

What is the parameter called? I don't see anything new in [Main Menu > Setup > General Setup Options > System Parameters]. Am I missing something?

Dale

**Comment by dalers** [comment]
I see the commit only affects /install/sql/config.sql. 

Will current users need a database upgrade to keep the schema the same as a new database?

**Comment by dalers** [comment]
Never mind last reply, the commas included in the string before and after the language ("fr_FR.utf8") were throwing me off....

**Comment by dalers** [comment]
> "Languages to Maintain Translations for Item Descriptions:"

Ah, obviously.... (in hindsight). Thanks Tim!

**Comment by dalers** [comment]
I'm ok to close issue now.

**Comment by andrewcouling** [comment]
> Can this issue be closed?

I will review later and confirm.

**Comment by andrewcouling** [comment]
The main issue (in the title) has been solved, therefore I will close this. There are other issues reported, but I have already raised separate issues for most of these. For anything remaining I will raise separate issues.

**Comment by andrewcouling** [comment]
> Btw, when navigating between Items and viewing individual Item details, I seem to constantly be triggering zoom/unzoom of an images moving the mouse around. I expect I'll get used to it but it might be nice to have a config value to turn off "auto-zoom" and only zoom an image when clicked. Fwiw.....

@dalers, I plan to raise a 'feature request' discussion related to this. My idea is to use a modal lightbox effect (css & js) to allow zooming of images, triggered by onclick instead of onhover.

**Comment by timschofield** [comment]
This is possibly just me getting carried away and doing something flashy because I could rather than because it was the best think to do :)
If the consensus is to stop it happening the change is easy. Its just a matter of changing the css/*/default.css files to remove the following lines:

img.StockImage:hover {
transform: scale(5);
box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

and it should stop.

Thanks
Tim
